#!/usr/bin/env bash

BASE_DIR=/autograder/biol7200-autograders

# update git repo
cd $BASE_DIR
git pull
# I think the next line is only necessary if you change the requirements after the first version of the assignment
pip3 install -r $BASE_DIR/requirements.txt

tar -xzf /autograder/source/ex3_data.tar.gz

# change to tests directory
cd $BASE_DIR/tests


python3 $BASE_DIR/gradescope_base/run_tests.py
